### ISSUE TITLE
bug 求助？

### ISSUE THREAD

**Issue by imnujf** [ShomyLiu/pytorch-relation-extraction#14]
Traceback (most recent call last):
  File "main_mil.py", line 203, in <module>
    fire.Fire()
  File "/usr/lib/python2.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/lib/python2.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/lib/python2.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "main_mil.py", line 67, in train
    data = select_instance(model, data, label)
  File "main_mil.py", line 117, in select_instance
    out = model(data)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhaojiapeng/pytorch-relation-extraction-master/models/PCNN_ONE.py", line 126, in forward
    x = [self.mask_piece_pooling(i, insMasks) for i in x]
  File "/home/zhaojiapeng/pytorch-relation-extraction-master/models/PCNN_ONE.py", line 85, in mask_piece_pooling
    masks = mask_embedding(mask).unsqueeze(-2) * 100
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/sparse.py", line 103, in forward
    self.scale_grad_by_freq, self.sparse
  File "/usr/lib64/python2.7/site-packages/torch/nn/_functions/thnn/sparse.py", line 59, in forward
    output = torch.index_select(weight, 0, indices.view(-1))
TypeError: torch.index_select received an invalid combination of arguments - got (torch.FloatTensor, int, torch.cuda.LongTensor), but expected (torch.FloatTensor source, int dim, torch.LongTensor index)

**Comment by 598807302** [comment]
同样的问题，请问您解决了吗

**Comment by ShomyLiu** [comment]
@imnujf @598807302  不好意思，最近在赶东西， 各位遇到的问题，可以先自行debug看看，或者检查下环境、数据。 过几天，会跟进这些bug

**Comment by imnujf** [comment]
@598807302 没有，您解决了可以加q联系我，3052847172

**Comment by imnujf** [comment]
@598807302 
![image](https://user-images.githubusercontent.com/26041804/48746850-24c1a280-ecac-11e8-939d-e60ac7a2d1b3.png)na'li
那里的问题，你在那加一个.cuda()就行了。

**Comment by 598807302** [comment]
@imnujf 好的谢谢
