### ISSUE TITLE
FilterNYT 问题

### ISSUE THREAD

**Issue by oddmen** [ShomyLiu/pytorch-relation-extraction#5]
您好！我在用FilterNYT数据集时有一些问题
我在使用 python main_att.py train --data="FilterNYT"  --batch_size=128命令训练\测试时，遇到以下问题

loading train data
loading finish
loading test data
loading finish
2018-10-11 10:30:03 train data: 65726; test data: 93574
Traceback (most recent call last):
  File "main_att.py", line 178, in <module>
    fire.Fire()
  File "/home/xyx/anaconda2/lib/python2.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/xyx/anaconda2/lib/python2.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/xyx/anaconda2/lib/python2.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "main_att.py", line 62, in train
    loss = model(data, label)
  File "/home/xyx/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xyx/pytorch-relation-extraction-master/models/PCNN_ATT.py", line 133, in forward
    self.bags_feature = self.get_bags_feature(x)
  File "/home/xyx/pytorch-relation-extraction-master/models/PCNN_ATT.py", line 203, in get_bags_feature
    bag_embs = self.get_ins_emb(data)                                   # get all instances embedding in one bag
  File "/home/xyx/pytorch-relation-extraction-master/models/PCNN_ATT.py", line 212, in get_ins_emb
    insEnt, _, insX, insPFs, insPool, mask = x
ValueError: need more than 5 values to unpack
希望能帮助我。

**Comment by ShomyLiu** [comment]
@oddmen  是这样的，因为修改过piece wise的计算方法，FilterNYT数据集这一块还没有来得及更新。未来几天会更新上去。 不过建议用大数据集NYT，目前来看 大部分工作都是基于这个来的。

**Comment by oddmen** [comment]
好的谢谢，另外您的绘图需要使用什么命令来使用呢

**Comment by ShomyLiu** [comment]
绘图的代码，在plot.ipynb里面。 使用jupyter 来运行的

**Comment by oddmen** [comment]
我将mask快速计算pcnn去除，使用旧的函数self.piece_max_pooling来计算是可行的吧

**Comment by ShomyLiu** [comment]
或者 直接checkout 提交mask之前的代码：https://github.com/ShomyLiu/pytorch-relation-extraction/tree/7e3ef1720d43690fc0da0d81e54bdc0fc0cf822a

**Comment by oddmen** [comment]
好的 多谢
