### ISSUE TITLE
bug修改问题

### ISSUE THREAD

**Issue by yuanqi1** [ShomyLiu/pytorch-relation-extraction#55]
老师您好！我在试运行您的这份代码的时候出现：
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1) 
具体在pcnn_one模型和pcnn_att模型中  
def init_word_emb(self):
      def p_2norm(path):
            v = torch.from_numpy(np.load(path))
            if self.opt.norm_emb:
                v = torch.div(v, v.norm(2, 1).unsqueeze(1))
                v[v != v] = 0.0
            return v
在您zeng2014版的pcnn这部分是没有这段的，请问您是否可以讲解一下这部分的用途以及如何修改v = torch.div(v, v.norm(2, 1).unsqueeze(1))

**Comment by ShomyLiu** [comment]
你好！
p_2norm 这个函数只是为了对embedding做一个归一化，如果不需要的话，可以直接设置为False，经过测试，效果影响不大。 至于遇到的这个bug，这里倒没有复现出来。

**Comment by yuanqi1** [comment]
您好！我屏蔽了
if self.opt.norm_emb:
v = torch.div(v, v.norm(2, 1).unsqueeze(1))
v[v != v] = 0.0
又出现RuntimeError: The expanded size of the tensor (50) must match the existing size (3256527) at non-singleton dimension 1

**Comment by ShomyLiu** [comment]
你好，能把报错的路径位置发一下吗，应该是你那边config的问题？

**Comment by yuanqi1** [comment]
此时，设置norm_emb=True
Traceback (most recent call last):
  File "main_mil.py", line 214, in <module>
    fire.Fire()
  File "G:\Anaconda\envs\tensorflow1.10\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "G:\Anaconda\envs\tensorflow1.10\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "G:\Anaconda\envs\tensorflow1.10\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "main_mil.py", line 43, in train
    model = getattr(models, 'PCNN_ONE')(opt)
  File "C:\Users\yuanqi\Desktop\pytorch-relation-extraction-master\models\PCNN_ONE.py", line 44, in __init__
    self.init_word_emb()
  File "C:\Users\yuanqi\Desktop\pytorch-relation-extraction-master\models\PCNN_ONE.py", line 78, in init_word_emb
    self.word_embs.weight.data.copy_(w2v)
RuntimeError: The expanded size of the tensor (50) must match the existing size (3256527) at non-singleton dimension 1

**Comment by yuanqi1** [comment]
我跑通了，谢谢您！

**Comment by ShomyLiu** [comment]
好的，那我close issue了
