### ISSUE TITLE
训练到第四个Epoch出现utils.py中的报错

### ISSUE THREAD

**Issue by Bawanglongdexiaozhuazi** [ShomyLiu/pytorch-relation-extraction#70]
2023-04-03 02:29:12 train data: 293175; test data: 96678
2023-04-03 02:38:48 Epoch 1/16: train loss: 611.8585879802704;
2023-04-03 02:48:07 Epoch 2/16: train loss: 424.87783089093864;
2023-04-03 02:57:30 Epoch 3/16: train loss: 373.0171359600499;
positive_num: 1761;  correct: 769.0
Traceback (most recent call last):
  File "main_att.py", line 176, in <module>
    fire.Fire()
  File "/root/anaconda3/envs/pre/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/anaconda3/envs/pre/lib/python3.7/site-packages/fire/core.py", line 480, in _Fire
    target=component.__name__)
  File "/root/anaconda3/envs/pre/lib/python3.7/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "main_att.py", line 80, in train
    save_pr(opt.result_dir, model.model_name, epoch, all_pre, all_rec, opt=opt.print_opt)
  File "/remote-home/Wei_SC/pytorch-relation-extraction-master/utils.py", line 15, in save_pr
    out = open('{}/{}_{}_{}_PR.txt'.format(out_dir, name, opt, epoch + 1), 'w')
FileNotFoundError: [Errno 2] No such file or directory: './out/PCNN_ATT_DEF_4_PR.txt'
请问如何解决呢？

**Comment by Bawanglongdexiaozhuazi** [comment]
已解决，将utils.py代码中这部分改一下就行：
def save_pr(out_dir, name, epoch, pre, rec, fp_res=None, opt=None):
    if opt is None:
        out = open('{}/{}_{}_PR.txt'.format(out_dir, name, epoch + 1), 'w')
    else:
        """if not os.path.exists(out_dir):
            os.makedirs(out_dir)"""
        out = open('{}/{}_{}_{}_PR.txt'.format(out_dir, name, opt, epoch + 1), 'w')
引号内是chatGPT说加上的。
